CC=mpigxx --std=c++11 -MMD -c -g -gdwarf-3 -fPIC

__CC_CUDA=nvcc --compiler-bindir /usr/bin -arch=sm_13
CC_CUDA=${__CC_CUDA} -c -g
CC_CUDA_DEPENDS=${__CC_CUDA} -M

LD=mpigxx -rdynamic

SYSTEM_INCLUDES= \
/usr/include \
/share/apps/cuda/cuda6/extras/CUPTI/include \
/share/apps/cuda/cuda6/include \
/share/apps/gsl/include


LIBS_PATH= \
${HOME}/lib \
/usr/lib64 \
/share/apps/gcc-4.9.1/lib64 \
/share/apps/cuda/cuda6/lib64 \
/share/apps/gsl/lib