#!/bin/bash

set -e

processors=$( python -c 'print ",".join(map(str,range(0,12)))' )
interval=2

while true; do
    mpstat -P $processors $interval 1 | tail -n 12 | awk '{print $2 "\t" $3 "\t" $4}'
    echo
    sleep $interval
done

