#!/bin/bash

if [ "$1" == "--no-show" ]; then
    flags="--no-show"
    shift
fi

trialsdir=$1

ls -dv $trialsdir/run* | (
    i=0
    while read x; do
        printf "$i\t"
        head -1 $x/genome/Fittest/fitness.txt | awk '{print $2}'
        i=$((i+1))
        done
) > /tmp/scores

$(dirname $0)/plot_file $flags /tmp/scores
