#!/bin/bash

trialsdir=$1

ls -v $trialsdir/run*/stats/stat.100 | (
    i=0
    while read x; do
        printf "$i\t"
        grep CurNeurGroups $x | awk '{print $3}'
        i=$((i+1))
        done
) > /tmp/neurgroups

$(dirname $0)/plot_file /tmp/neurgroups
