#!/bin/bash

if [ "$1" == "--no-show" ]; then
    flags="--no-show"
    shift
fi

trialsdir=$1

ls -dv $trialsdir/run* | (
    i=0
    while read x; do
        printf "$i\t"
        cat $x/velocity.txt | awk '{print $1}'
        i=$((i+1))
        done
) > /tmp/velocity

$(dirname $0)/plot_file $flags /tmp/velocity
